### ISSUE TITLE
Docker compose fails to start

### ISSUE THREAD

**Issue by Chen-Jianxiong** [tigergraph/CoPilot#149]
I am very grateful to the TigerGraph team for developing such a good project, but I have encountered some problems while using it.

When start a service with docker-compose up, I get a `copilot_1` error：`python: can't open file '/code/app.py': [Errno 2] No such file or directory`，The docker container: `copilot_copilot` then closes automatically.
When I try to start it several times, I can occasionally pass the case temporarily, but I cannot visit 'http://localhost/docs'
Could you please tell me whether the current project can be used normally through Docker deployment?

Looking forward to the update of the project or your reply.

**Comment by billshitg** [comment]
hmmm, weird error. Could you shut down all services `docker compose down`, and then update the images `docker compose pull` to make sure all images are latest?

**Comment by parkererickson-tg** [comment]
Stale. Closing for now, if you still have a problem please reopen.
