### ISSUE TITLE
db_config.json does not support custom ports

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [tigergraph/CoPilot#173]
Our on-premise instance is provisioned with non-standard ports, but copilot's `db_config.json` does not support specifying ports.

**Comment by parkererickson-tg** [comment]
Thanks for your report @OrkhanAlikhanov! We will take care of it.

**Comment by parkererickson-tg** [comment]
This has been merged and resolved in the latest docker image.

**Comment by OrkhanAlikhanov** [comment]
Incredible turn around time! Thanks!
