### ISSUE TITLE
Healthcheck uses hardcoded milvus config

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [tigergraph/CoPilot#235]
I think it should load config from the file instead of hardcoding it at:

https://github.com/tigergraph/CoPilot/blob/81fba191b9621cd2056f328115936d76d68b4ea2/app/routers/root.py#L22

**Comment by billshitg** [comment]
It is fixed in this PR https://github.com/tigergraph/CoPilot/pull/237. Will port to the dev and main branch next.

**Comment by billshitg** [comment]
Close as it is fixed
