### ISSUE TITLE
InquiryAI call fails with "Error running query HNSW_Overlap_Search: 404 Client Error"

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [tigergraph/CoPilot#238]
Sometimes Inquiry AI query like `conn.query('How many edges are there')` fails with `Error running query HNSW_Overlap_Search: 404 Client Error`. From the source code it looks like `HNSW_Overlap_Search` is part of `supportai`, and it's mistakenly called.

I think the mistake stems from these lines: 

https://github.com/tigergraph/CoPilot/blob/81fba191b9621cd2056f328115936d76d68b4ea2/app/agent/agent_graph.py#L279-L280

It looks like the mapping should be swapped.

**Comment by parkererickson-tg** [comment]
This should be fixed now in the dev branch - we check if supportai is enabled on the graph the question is being asked to. Those lines are used to try the other approach in case the original method did not execute correctly. Thanks for the report!
