### ISSUE TITLE
Please correct these function names:  [reserved 'tg_']: tg_searchInMilvus

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [tigergraph/CoPilot#239]
UDF definition starts with `tg_`:
https://github.com/tigergraph/CoPilot/blob/81fba191b9621cd2056f328115936d76d68b4ea2/udfs/milvus/rest/ExprFunctions.hpp#L3

But [docs](https://docs.tigergraph.com/gsql-ref/current/querying/func/query-user-defined-functions#:~:text=Beginning%20in%20TigerGraph%20version%203.9%2C%20user%2Ddefined%20functions%20may%20not%20begin%20with%20the%20prefix%20tg_.) say:
>Beginning in TigerGraph version 3.9, user-defined functions may not begin with the prefix `tg_`.

We are on `3.10.1`.

**Comment by billshitg** [comment]
Thanks for pointing it out! This is to be consistent with TG 4.x and above as this function will be included out of the box. However, it is too late to include it in 3.x but you can still install it in GSQL as `PUT tg_ExprFunctions FROM "..."` and 
`PUT tg_ExprUtil FROM "..."`. Accordingly, you will need to enable it by setting `gadmin config set GSQL.UDF.EnablePutTgExpr true`. More detailed documentation will be added in our next release.

**Comment by OrkhanAlikhanov** [comment]
Thank you having a look. TG 4.x? I do not see it at https://hub.docker.com/r/tigergraph/tigergraph/tags. Is it not released yet? Do you know when we can expect it?

**Comment by billshitg** [comment]
No, it is not released, but will be in the upcoming months. As it will be major overhaul, there are a lot of testing going on and I cannot give you an exact date right now. The announcement for it will go out soon. Thanks for the interest!
